### ISSUE TITLE
Unregistration may possibly be failing silently?

### ISSUE THREAD

**Issue by Fuzion24** [daveio/whisperpush-unregister#11]
I've successfully unregistered according to your script:

```
 ➜  whisperpush-unregister git:(master) ruby whisperpush_unregister.rb -m unregister -p +1XXXXXXXXXX --code YYYYYY
#<URI::HTTPS:0x007fc610860e60 URL:https://whisperpush.cyanogenmod.org/v1/accounts/code/YYYYYY>
Unregistering gcm with 20 rounds....................done.
Unregistering apn with 20 rounds....................done.
You should now be unregistered from CyanogenMod's WhisperPush service.
```

However, I still get (when attempting registration with TextSecure): 
"The number is already registered on a different TextSecure server (Cyanogenmod?).  You must unregister there before registering here."

I was curious if you've ran into this or had a work around?

I'm also curious about the rounds?  Why do you have to send the unregister request so many times?

**Comment by apeltzer** [comment]
Still not working, unfortunately -.- Even the web interface says: Unregistered, yet nothing happens.

**Comment by Fuzion24** [comment]
Somehow, after a few weeks of waiting, my number was unregistered from CM's server.  I am now able to use TextSecure

**Comment by JC5** [comment]
After running the script I too did not get unregistered. I used the web interface mentioned above, but this did not work either. I'll keep you posted, maybe it'll take some weeks as well.

The script however, ran like a charm!

**Comment by sh0nuff** [comment]
After having no luck with any of these solutions months ago,  I bit the
bullet,  installed CM11 on my phone,  and unregistered that way. Odd,  as
it told me I wasn't on their servers to begin with when I sent the request
to be removed,  but after I wiped back to my normal ROM,  I was able to
register with TextSecure without an issue.

**Comment by mohlerm** [comment]
Also tried all 3 solutions, doesn't work for me yet.

**Comment by daveio** [comment]
Glad it finally worked, sadly I have no input on the remote systems so I can't speak for them.
