### ISSUE TITLE
Totally out of my element

### ISSUE THREAD

**Issue by sh0nuff** [daveio/whisperpush-unregister#8]
Despite feeling pretty comfortable with all sorts of mobile and computing platforms/processes, I have always found development to be difficult to understand..

As such, I find this to be way over my head. Following the steps, this is the log that's generated when I attempt to get a confirmation

irb(main):002:0> ruby whisperpush_unregister.rb --mode getconfirm --phone-numb>
SyntaxError: (irb):2: syntax error, unexpected tIDENTIFIER, expecting keyword_do
 or '{' or '('
...unregister.rb --mode getconfirm --phone-number +16132760077
...                               ^
(irb):2: syntax error, unexpected tINTEGER, expecting keyword_do or '{' or '('
        from C:/Ruby21-x64/bin/irb:11:in `<main>'
irb(main):003:0>
(irb):1: syntax error, unexpected tINTEGER, expecting keyword_do or '{' or '('
        from C:/Ruby21-x64/bin/irb:11:in `<main>'
irb(main):002:0>"

**Comment by daveio** [comment]
Don't execute the command inside irb, just do it from your shell.
